CURSOS = [
    "Artes Visuais - Bacharelado", "Artes Visuais - Licenciatura", "Desenho Industrial",
    "Letras - Bacharelado", "Letras - Espanhol", "Letras - Inglês", "Letras - Português", "Teatro",
    "Ciências Biológicas", "Estatística", "Física - Bacharelado", "Física - Licenciatura - Diurno",
    "Física - Licenciatura - Noturno", "Geografia - Bacharelado", "Geografia - Licenciatura",
    "Matemática - Bacharelado", "Matemática - Licenciatura - Diurno", "Matemática - Licenciatura - Noturno",
    "Meteorologia", "Química - Bacharelado", "Química - Licenciatura", "Química Industrial",
    "Tecnologia em Processos Químicos", "Agronomia/CCR", "Engenharia Florestal/CCR", "Medicina Veterinária",
    "Tecnologia em Agronegócio", "Tecnologia em Alimentos", "Zootecnia/CCR", "Enfermagem/CCS",
    "Fisioterapia", "Fonoaudiologia", "Medicina", "Odontologia", "Terapia Ocupacional",
    "Administração - Diurno/CCSH", "Administração - Noturno/CCSH", "Arquivologia",
    "Ciências Contábeis - Diurno", "Ciências Contábeis - Noturno", "Ciências Econômicas - Diurno",
    "Ciências Econômicas - Noturno", "Ciências Sociais - Bacharelado", "Ciências Sociais - Licenciatura",
    "Direito - Diurno", "Direito - Noturno", "Filosofia - Bacharelado", "Filosofia - Licenciatura",
    "História - Licenciatura", "Jornalismo/CCSH", "Produção Editorial", "Psicologia",
    "Publicidade e Propaganda", "Relações Internacionais", "Relações Públicas/CCSH", "Serviço Social",
    "Tecnologia em Gestão de Turismo", "Educação Especial - Diurno", "Educação Especial - Noturno",
    "Pedagogia - Diurno", "Pedagogia - Noturno", "PEG", "Dança - Licenciatura",
    "Educação Física - Bacharelado", "Educação Física - Licenciatura", "Arquitetura e Urbanismo/CS",
    "Engenharia Agrícola/CS", "Engenharia de Transportes e Logística/CS", "Engenharia Elétrica/CS",
    "Engenharia Mecânica/CS", "Arquitetura e Urbanismo/CT", "Ciência da Computação",
    "Engenharia Acústica", "Engenharia Aeroespacial", "Engenharia Civil", "Engenharia da Computação",
    "Engenharia de Controle e Automação", "Engenharia de Produção", "Engenharia de Telecomunicações",
    "Engenharia Elétrica/CT", "Engenharia Mecânica/CT", "Engenharia Química",
    "Engenharia Sanitária e Ambiental", "Sistemas de Informação/CT", "Tecnologia em Eletrônica Industrial",
    "Tecnologia em Fabricação Mecânica", "Tecnologia em Redes de Computadores", "Agronomia/FW",
    "Engenharia Ambiental e Sanitária/FW", "Engenharia Florestal/FW", "Jornalismo/FW",
    "Relações Públicas/FW", "Sistemas de Informação/FW", "Administração - Diurno/PM",
    "Administração - Noturno/PM", "Ciências Biológicas/PM", "Ciências Econômicas/PM",
    "Enfermagem/PM", "Nutrição/PM", "Zootecnia/PM", "Tecnologia de Geoprocessamento",
    "Tecnologia em Gestão Ambiental", "Tecnologia em Gestão de Cooperativas",
    "Tecnologia em Sistemas para Internet"
]